kumuluzee:
  name: accountoptions-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/accountoptionsDS
      connection-url: jdbc:postgresql://docker.for.mac.localhost:5432/accountoptions
      username: postgres
      password: postgres
      max-pool-size: 20
